// export type callback = (message: String | null, err?: any) => void;

export interface CapacitorAxaMobileSdkPlugin {

  echo(options: { value: string }): Promise<{ value: string }>;


  /**
   * Use this API to disable the SDK.
   * When disabled, the SDK no longer does any tracking of the application,
   * or user interaction.
   *
   */
   disableSDK(): void;


  /**
   * Use this API to enable SDK.
   * The SDK is enabled by default. You need to call this API
   * only if you called disableSDK earlier.
   *
   */
   enableSDK(): void;


  /**
   * Use this API to determine if the SDK is enabled or not.
   *
   * Returns a boolean value
   *
   */
   isSDKEnabled(): Promise<boolean>
  

  /**
   * Use this API to get the unique device ID generated by the SDK
   *
   * Returns a string value
   *
   */
   getDeviceId(): Promise<string>


  /**
   * Use this API to get the customer ID for this session.
   * Returns a string value. If the customer ID is not set, this API returns a null value.
   *
   */
   getCustomerId(): Promise<string>;


  /**
   * Use this API to set the customer ID for this session.
   *
   * @param customerId is a string containing the customer ID
   * If an empty string is passed, the customer iD is reset.
   * Retruns a (SDKError value)
   *
   */
   setCustomerId(options: {customerId: string}): Promise<CAMDOSDKErrorCallback>;


  /**
   * Use this API to set a custom session attribute.
   *
   * @param name is a string containing the attribute name
   * @param value is string containing the attribute value
   * callback is a function which expects an (SDKError value)
   * 
   */
   setSessionAttribute(options: { name: string, value: string}): Promise<CAMDOSDKErrorCallback>;


  /**
   * Use this API to stop collecting potentially sensitive data.
   *
   * The following data is not collected when the app enters a private zone
   *    - Screenshots
   *    - Location information including GPS and IP addresses
   *    - Value in the text entry fields
   *
   */
   enterPrivateZone(): void;


  /**
   * Use this API to start collecting all data again
   */
   exitPrivateZone(): void;

  
  /**
   * Use this API to determine if the SDK is in a private zone.
   *
   * Returns a boolean value
   *
   */
   isInPrivateZone(): Promise<boolean>;


  /**
   * Use this API to get the SDK computed APM header in key value format.
   * Returns dictionary or map of key, value pairs
   * Returns an empty string if apm header cannot be computed
   *
   */
   getAPMHeader(): Promise<object>;


  /**
   * Use this API to add custom data to the SDK computed APM header.
   * @param data is a non-empty string in the form of "key=value".
   * data will be appended to the APM header separated by a semicolon (;).
   *
   */
   addToAPMHeader(options: {data: object}): void;


  /**
   * Use this API to set the ssl pinning mode and array of pinned values.
   * This method expects array of values depending on the pinningMode
   *
   * @param pinningMode is one of the CAMDOSSLPinning modes described below
   * @param pinnedValues is an array as required by the pinning mode
   *
   * Supported pinning modes:
   * CAMDOSSLPinningModePublicKey OR CAMDOSSLPinningModeCertificate
   *          - array of certificate data (NSData from SeccertificateRef)
   *          - or, certificate files(.cer) to be present in the resource bundle
   *
   * CAMDOSSLPinningModeFingerPrintSHA1Signature
   *          - array of SHA1 fingerprint values
   *
   * CAMDOSSLPinningModePublicKeyHash
   *          - array of PublicKeyHashValues
   */
   setSSLPinningMode(options: {pinningMode: CAMDOSSLPinningMode, pinnedValues: object[] }): void;


  /**
   * Use this API to stop the current session.
   * No data will be logged until the startSession API is called
   *
   */
   stopCurrentSession(): void;


  /**
   * Use this API to start a new session.
   * If a session is already in progress, it will be stopped and new session is started
   *
   */
   startNewSession(): void;


  /**
   * Convenience API to stop the current session in progress and start a new session
   * Equivalent to calling stopCurrentSession() and startNewSession()
   */
   stopCurrentAndStartNewSession(): void;


  /**
   * Use this API to start a transaction with a specific name
   *
   * @param transactionName is a string to indicate the transaction being processed
   * @param serviceName is a string to indicate the service or application being applied
   * Returns a CAMDOSDKCallback
   *
   * If successful, completed = YES and error is nil.
   * In case of failure, completed = NO and error will have NSError object with
   * domain, code and localizedDescription.
   *
   */
   startApplicationTransaction(options: {transactionName: string, serviceName?: string} ): Promise<CAMDOSDKCallback>;


  /**
   * Use this API to stop a transaction with a specific name and an optional failure string
   *
   * @param transactionName is a string to indicate the transaction being processed
   * @param failureString is a string to indicate the failure name, message or type
   * Returns a CAMDOSDKCallback
   *
   * If successful, completed = YES and error is nil.
   * In case of failure, completed = NO and error will have NSError object with
   * domain, code and localizedDescription.
   *
   */
   stopApplicationTransaction(options: {transactionName: string, failure?: string}): Promise<CAMDOSDKCallback>; 

  
  /**
   * Use this API to provide feedback from the user after a crash
   *
   * @param feedback is a string containing any customer feedback for the crash
   *
   * The App has to register for CAMAA_CRASH_OCCURRED notification
   * and collect the feedback from the user while handling the notification
   *
   */
   setCustomerFeedback(options: {feedback: string}): void;


  /**
   * Use this API to set Location of the Customer/User
   * using postalCode and countryCode.
   *
   * @param postalCode is the country's postal code, e.g. zip code in the US
   * @param countryCode is the two letter international code for the country
   *
   */
   setCustomerLocation(options: {postalCode: string, countryCode: string}): void;

  /**
   * Use this API to send a screen shot of the current screen
   *
   * @param name is a string to indicate the desired name for the screen
   * @param quality is a CAMDOSDKImageQualityType indicating the quality of the image
   * The following values for imageQuality are defined:
   * - CAMAA_SCREENSHOT_QUALITY_HIGH
   * - CAMAA_SCREENSHOT_QUALITY_MEDIUM
   * - CAMAA_SCREENSHOT_QUALITY_LOW
   * - CAMAA_SCREENSHOT_QUALITY_DEFAULT
   *
   * The default value is CAMAA_SCREENSHOT_QUALITY_LOW.
   *
   * Returns a CAMDOSDKCallback
   * 
   * If successful, completed = YES and error is nil.
   * In case of failure, completed = NO and error will have NSError object with
   * domain, code and localizedDescription.
   *
   */
   sendScreenShot(options: {name: string, quality: CAMDOSDKImageQualityType}): Promise<CAMDOSDKCallback>;

  
  /**
   * Use this API to create a custom app flow with dynamic views
   *
   * @param viewName is the name of the view that was loaded
   * @param loadTime is the time it took to load the view
   * Returns a CAMDOSDKCallback
   * 
   * If successful, completed = YES and error is nil.
   * In case of failure, completed = NO and error will have NSError object with
   * domain, code and localizedDescription.
   *
   */
   viewLoaded(options: {viewName: string, loadTime: number}): Promise<CAMDOSDKCallback>; 


  /**
   * Use this API to set the name of a view to be ignored
   * @param viewName is Name of the view to be ignored
   * Screenshots and transitions of the views that are in ignore list are not captured
   *
   */
   ignoreView(options: {viewName: string}): void;


  /**
   * Use this API to provide a list of view names to be ignored.
   * @param viewNames is a list (an array) of names of the views to be ignored.
   * Screenshots and transitions of the views that are in the
   * ignore list are not captured
   *
   */
   ignoreViews(options: {viewNames: string[] }): void; 


  /**
   * Use this API to determine if automatic screenshots are enabled by policy.
   * 
   * Returns a boolean value
   * Returns YES if screenshots are enabled by policy.  Otherwise returns NO
   * 
   */
   isScreenshotPolicyEnabled(): Promise<boolean>; 

  /**
   * Use this API to add a custom network event in the current session
   *
   * @param url is a string reprentation of the network URL to be logged
   * @param status is an integer value indicating the status, e.g. 200, 404, etc.
   * @param responseTime is an integer value representing the response time
   * @param inBytes is an integer value representing the number of bytes input
   * @param outBytes is an integer value representing the number of bytes output
   * Returns a CAMDOSDKCallback
   * 
   * If successful, completed = YES and error is nil.
   * In case of failure, completed = NO and error will have NSError object with
   * domain, code and localizedDescription.
   *
   */
   logNetworkEvent(options: {url: string, status: number, responseTime: number, inBytes: number, outBytes: number} ): Promise<CAMDOSDKCallback>;


  /**
   * Use this API to add a custom text metric in the current session
   *
   * @param textMetricName is a string to indicate a text metric name
   * @param textMetricValue is a string to indicate a text metric value
   * @param attributes is a Map or Dictionary used to send any extra parameters
   * Returns a CAMDOSDKCallback
   * 
   * If successful, completed = YES and error is nil.
   * In case of failure, completed = NO and error will have NSError object with
   * domain, code and localizedDescription.
   *
   */
   logTextMetric(options: {textMetricName: string, value: string, attributes?: object}): Promise<CAMDOSDKCallback>;


  /**
   * Use this API to add a custom numeric metric value in the current session
   *
   * @param numericMetricName is a string to indicate a numeric metric name
   * @param numericMetricValue is a numeric value, e.g. 3.14159, 2048.95, or 42, etc.
   * @param attributes is a Map or Dictionary used to send any extra parameters
   * Returns a CAMDOSDKCallback
   * 
   * If successful, completed = YES and error is nil.
   * In case of failure, completed = NO and error will have NSError object with
   * domain, code and localizedDescription.
   *
   */
   logNumericMetric(options: {numericMetricName: string, value: number, attributes?: object}): Promise<CAMDOSDKCallback>;


  /**
   * Use this API to force an upload event.
   * This is bulk/resource consuming operation and should be used with caution
   *
   * @param callback is a function which expects a response object and an error object
   *
   * Returns:
   * - response is a key,value paired map or dictionary object
   *  the Key 'CAMDOResponseKey' holds any URLResponse information
   *  the key 'CAMDOTotalUploadedEvents' holds the total number of events uploaded
   * - error is nil if the API call is successful, otherwise is an NSError object
   * with domain, code and localizedDescription.
   *
   */
  uploadEvents(): Promise<CAMDOUploadEventsCallback>;


  /**
   * Use this API to set your delegate instance to handle auth challenges.
   * Use it when using SDKUseNetworkProtocolSwizzling option
   *
   * @param delegate is an iOS native object or module which responds to the  NSURLSessionDelegate protocols.
   *
   */
   setNSURLSessionDelegate(options:{delegate: string}): void;


  /**
   * Use this API to set Geographic or GPS Location of the Customer
   *
   * @param latitude is the geographic latitude from -90.0 to 90.0 degrees
   * @param logitude is the geographic longitude from -180.0 to 180.0 degrees
   *
   */
   setLocation(options: {latitude: number, longitude: number}): void;


  /**
   * Use this API to programmatically enable or disable automatic screen captures.
   *
   * @param captureScreen is a boolean value to enable/disable automatic screen captures.
   *
   * Normally the policy determines whether automatic screen captures are performed.
   * Use this API to override the policy, or the current setting of this flag.
   *
   */
   enableScreenShots(captureScreen: boolean): void;
    

  /**
   * Use this API to create a custom app flow with dynamic views
   *
   * During a loadView call, on iOS only, screen captures are controlled
   * by policy, or the setting of the enableScreenShots API call.
   * The iOS SDK allows the calling API to disable automatic screen
   * captures if they are currently enabled.
   * This API call prevents any screen capture during the loadView call
   * by overriding policy for this invocation.
   *
   * @param viewName is the name of the view that was loaded
   * @param loadTime is the time it took to load the view
   * Returns a CAMDOSDKCallback
   * 
   * If successful, completed = YES and error is nil.
   * In case of failure, completed = NO and error will have NSError object with
   * domain, code and localizedDescription.
   *
   */
   viewLoadedWithoutScreenCapture(options:{viewName: string, loadTime: number}): Promise<CAMDOSDKCallback>;


   logUIEvent(options: {eventType: string, value: string} ): void;

}



// Enums for SDK Errors
export enum SDKError {
    ErrorNone,
    ErrorNoTransactionName,
    ErrorTransactionInProgress,
    ErrorFailedToTakeScreenshot,
    ErrorInvalidValuesPassed
}

//Enums for the pinningMode during the SSL handshake
export enum CAMDOSSLPinningMode {
  CAMDOSSLPinningModeNone,    // default
  CAMDOSSLPinningModePublicKey,
  CAMDOSSLPinningModeCertificate,
  CAMDOSSLPinningModeFingerPrintSHA1Signature,
  CAMDOSSLPinningModePublicKeyHash
}

export interface CAMDOSDKCallback {
  completed: boolean;
  error: string;
}

export interface CAMDOUploadEventsCallback {
  response: object;
  error: string;
}

export interface CAMDOSDKErrorCallback {
  error: SDKError;
}

export type CAMDOSDKImageQualityType =
| 'CAMAA_SCREENSHOT_QUALITY_HIGH'
| 'CAMAA_SCREENSHOT_QUALITY_MEDIUM'
| 'CAMAA_SCREENSHOT_QUALITY_LOW'
| 'CAMAA_SCREENSHOT_QUALITY_DEFAULT'

